"""Added subtasks

Revision ID: 461649916e81
Revises: 6b193daacbf9
Create Date: 2025-10-13 17:22:21.588593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '461649916e81'
down_revision: Union[str, Sequence[str], None] = '6b193daacbf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('themes')
    op.create_foreign_key(None, 'attachments', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'categories', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'codes', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'projects', 'users', ['owner_id'], ['id'])
    op.create_foreign_key(None, 'subtasks', 'tasks', ['task_id'], ['id'])
    op.alter_column('tasks', 'start',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('tasks', 'end',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_foreign_key(None, 'tasks', 'users', ['creator_id'], ['id'])
    op.create_foreign_key(None, 'tasks', 'users', ['performer_id'], ['id'])
    op.create_foreign_key(None, 'userprojectassociations', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'userprojectassociations', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.alter_column('tasks', 'end',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('tasks', 'start',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_constraint(None, 'subtasks', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_constraint(None, 'codes', type_='foreignkey')
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_constraint(None, 'attachments', type_='foreignkey')
    op.create_table('themes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('max_voices', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('time_start_idea', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('time_start_vote', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('time_end_vote', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('is_archived', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('themes_project_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('themes_pkey'))
    )
    # ### end Alembic commands ###
