"""Added theme and comment table

Revision ID: ab2a996e7f63
Revises: 461649916e81
Create Date: 2025-10-25 15:59:24.405310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ab2a996e7f63'
down_revision: Union[str, Sequence[str], None] = '461649916e81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('logs')
    op.create_foreign_key(None, 'projects', 'attachments', ['icon_id'], ['id'])
    op.create_foreign_key(None, 'subtasks', 'tasks', ['task_id'], ['id'])
    op.create_foreign_key(None, 'tag_tasks', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('tasks_project_id_fkey'), 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'users', 'attachments', ['icon_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key(op.f('tasks_project_id_fkey'), 'tasks', 'projects', ['project_id'], ['id'])
    op.drop_constraint(None, 'tag_tasks', type_='foreignkey')
    op.drop_constraint(None, 'subtasks', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_table('logs',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('added', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('logs_pkey'))
    )
    # ### end Alembic commands ###
